add_rules("mode.debug", "mode.release")

add_includedirs("./src")
add_includedirs("../../lib/lw_oopc")
add_includedirs("../../src/")
add_includedirs("../../src/interface")
add_includedirs("./libs/cmsis")

target("lua_lib")
    add_defines("KEIL_MDK=1")
    add_rules("mdk.static")
    add_files("../../src/onelua.c")
    add_files("../../src/interface/*.c")
    set_runtimes("microlib")
target_end()   


target("microlua_stm32")
    add_deps("lua_lib")
    add_rules("mdk.binary")
    add_files("src/*.c", "src/*.s")
    add_includedirs("libs/cmsis")
    set_runtimes("microlib")
    after_build(function (target)
        print("---------- MicroLua STM32 ------------")
        print(os.curdir())
    end)target_end()
target_end()
